In [5]:
 num1 = float(input())
num2 = float(input())
divv = num1/num2
print(f"divv: {num1}/{num2}={divv}")

 45
 55


divv: 45.0/55.0=0.8181818181818182


In [18]:
random_float = random.random()  # Generates a random float between 0.0 and 1.0
print(random_float)


0.9130237473516872


In [12]:
import random
random_integer = random.randint(1, 100)  # Generates a random integer between 1 and 100 inclusive
print(random_integer)


55


In [15]:
random_uniform = random.uniform(1.0, 10.0)  # Generates a random float between 1.0 and 10.0
print(random_uniform)


5.5446536809416616


In [17]:
items = ['apple', 'banana', 'cherry']
random_choice = random.choice(items)  # Randomly selects one element from the list
print(random_choice)


cherry


In [20]:
# Define two variables
a = input()
b = input()

# Print the original values
print(f"Before swapping: a = {a}, b = {b}")

# Swap the variables
a, b = b, a

# Print the swapped values
print(f"After swapping: a = {a}, b = {b}")


 55
 12


Before swapping: a = 55, b = 12
After swapping: a = 12, b = 55


In [22]:
print(a,b) # using temporary variable
temp=a
a=b
b=temp
print(a,b)

55 12
12 55


In [27]:
kilometers = float(input())  # convert kilometers to meters
conversion_factor = 0.621371
miles = kilometers * conversion_factor
print(miles)

 55


34.175405


In [29]:
# convert celsius to fahrenheit
celsius = float ( input ())
fahrenheit = (celsius * 9/5 ) + 32
print(fahrenheit)

 45


113.0


In [32]:
# display calendar
import calendar
year = int (input())
month = int (input())
cal = calendar.month(year,month)
print(cal)

 2019
 05


      May 2019
Mo Tu We Th Fr Sa Su
       1  2  3  4  5
 6  7  8  9 10 11 12
13 14 15 16 17 18 19
20 21 22 23 24 25 26
27 28 29 30 31



In [34]:
# Take user input for the year
year = int(input("Enter a year: "))

# Check if the year is a leap year
if (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0):
    print(f"{year} is a leap year.")
else:
    print(f"{year} is not a leap year.")


Enter a year:  2018


2018 is not a leap year.


In [36]:
num = int(input("Enter a number : "))
for i in range(0,11):
    print(f"{num}*{i} = { num* i } ")

Enter a number :  8


8*0 = 0 
8*1 = 8 
8*2 = 16 
8*3 = 24 
8*4 = 32 
8*5 = 40 
8*6 = 48 
8*7 = 56 
8*8 = 64 
8*9 = 72 
8*10 = 80 


In [38]:
# Define two dictionaries
dict1 = {'a': 1, 'b': 2}
dict2 = {'c': 3, 'd': 4}

# Merge dict2 into dict1 using the update method
dict1.update(dict2)

# Print the merged dictionary
print("Merged dictionary using update():", dict1)


Merged dictionary using update(): {'a': 1, 'b': 2, 'c': 3, 'd': 4}


In [39]:
# Define two dictionaries
dict1 = {'a': 1, 'b': 2}
dict2 = {'c': 3, 'd': 4}

# Merge dictionaries using dictionary unpacking
merged_dict = {**dict1, **dict2}

# Print the merged dictionary
print("Merged dictionary using unpacking:", merged_dict)
#The expression {**dict1, **dict2} creates a new dictionary.
#The ** operator unpacks the key-value pairs from dict1 and dict2 into the new dictionary.
#If there are any overlapping keys, the values from dict2 will overwrite the values from dict1.


Merged dictionary using unpacking: {'a': 1, 'b': 2, 'c': 3, 'd': 4}


In [40]:
# Example key-values list
key_values_list = [('a', 1), ('b', 2), ('c', 3), ('d', 4), ('e', 5)]

# Initialize an empty dictionary to store the flattened key-value pairs
flat_dict = {}

# Iterate through each pair in the key-values list and add them to the flat dictionary
for pair in key_values_list:
    # Check if the pair contains exactly two elements (a key and a value)
    if len(pair) == 2:
        key, value = pair
        flat_dict[key] = value
    else:
        print(f"Ignoring invalid pair: {pair}")

# Print the flat dictionary
print("Flat dictionary:", flat_dict)


Flat dictionary: {'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5}


In [49]:
original_dict = {'b': 2, 'a': 1, 'd': 4, 'c': 3}
sorted(original_dict)


['a', 'b', 'c', 'd']

In [48]:
original_dict = {'b': 2, 'a': 1, 'd': 4, 'c': 3}
sorted_keys = sorted(original_dict)

for key in sorted_keys:
    print(original_dict[key])


1
2
3
4


In [44]:
# Original dictionary
original_dict = {'b': 2, 'a': 1, 'd': 4, 'c': 3}

# Sort the dictionary by keys
sorted_dict_by_keys = {key: original_dict[key] for key in sorted(original_dict)}

# Print the sorted dictionary by keys
print("Sorted dictionary by keys:", sorted_dict_by_keys)


Sorted dictionary by keys: {'a': 1, 'b': 2, 'c': 3, 'd': 4}


In [53]:
number = int(input("Enter a number: "))
num_str = str(number)
print(num_str)
print(len(num_str))

Enter a number:  455


455
3


In [62]:
# python 3 program
# to check whether the given number is armstrong or not
# without using power function

n = 153 # or n=int(input()) -> taking input from user
s = n # assigning input value to the s variable
b = len(str(n))
sum1 = 0
while n != 0:
	r = n % 10
	sum1 = sum1+(r**b)
	n = n//10
if s == sum1:
	print("The given number", s, "is armstrong number")
else:
	print("The given number", s, "is not armstrong number")

# This code is contributed by Gangarajula Laxmi


The given number 153 is armstrong number


In [63]:
n = 1
n = n%10
print(n)

1


In [ ]:
The Fibonacci numbers are the numbers in the following integer sequence. 0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, ……..
In mathematical terms, the sequence Fn of Fibonacci numbers is defined by the recurrence relation.

Fn = Fn-1 + Fn-2

with seed values : F0 = 0 and F1 = 1.

In [66]:
nterms = int(input("How many terms? "))  # Get the number of terms from the user
n1, n2 = 0, 1  # Initialize the first two terms of the Fibonacci sequence
count = 0  # Initialize a counter

# Check if the number of terms is valid
if nterms <= 0:
    print("Please enter a positive integer")
# If there is only one term, return n1
elif nterms == 1:
    print("Fibonacci sequence upto", nterms, ":")
    print(n1)
# Generate the Fibonacci sequence
else:
    print("Fibonacci sequence:")
    while count < nterms:
        print(n1)
        nth = n1 + n2  # Calculate the next term in the sequence
        # Update values for the next iteration
        n1 = n2
        n2 = nth
        count += 1  # Increment the counter


How many terms?  6


Fibonacci sequence:
0
1
1
2
3
5


In [69]:
nterms = int(input("How many terms? "))  # Get the number of terms from the user
n1, n2 = 0, 1  # Initialize the first two terms of the Fibonacci sequence
count = 0  # Initialize a counter

# Check if the number of terms is valid

while (nterms > 1) and (count < nterms):
        print(n1)
        nth = n1 + n2  # Calculate the next term in the sequence
        # Update values for the next iteration
        n1 = n2
        n2 = nth
        count += 1  # Increment the counter

How many terms?  5


0
1
1
2
3


In [70]:
#Write a Python Program to Find the Sum of Natural Numbers 
limit = int(input("Enter the limit: "))  # Get the limit from the user
sum = 0  # Initialize the sum

# Use a for loop to calculate the sum of natural numbers
for i in range(1, limit + 1):
    sum += i

# Print the sum
print("The sum of natural numbers up to", limit, "is:", sum)


Enter the limit:  55


The sum of natural numbers up to 55 is: 1540


In [71]:
# Get the character from the user
char = input("Enter a character: ")

# Convert the character to its ASCII value
ascii_value = ord(char)

# Print the ASCII value
print("The ASCII value of", char, "is:", ascii_value)


Enter a character:  u


The ASCII value of u is: 117


In [72]:
# Function to calculate the factorial of a number
def factorial(n):
    fact = 1
    for i in range(1, n + 1):
        fact *= i
    return fact

# Get the number from the user
num = int(input("Enter a number: "))

# Check if the number is negative
if num < 0:
    print("Factorial is not defined for negative numbers.")
else:
    # Calculate and print the factorial
    fact = factorial(num)
    print("Factorial of", num, "is:", fact)


Enter a number:  16


Factorial of 16 is: 20922789888000


In [75]:
def bodymassindex(height, weight):
    return round((weight / height ** 2), 2)

h = float(input("Enter your height in meters: "))
w = float(input("Enter your weight in kg: "))

print("Welcome to the BMI calculator.")

bmi = bodymassindex(h, w)
print("Your BMI is:", bmi)

if bmi <= 18.5:
    print("You are underweight.")
elif 18.5 < bmi <= 24.9:
    print("Your weight is normal.")
elif 25 < bmi <= 29.9:
    print("You are overweight.")
else:
    print("You are obese.")



Enter your height in meters:  1.7
Enter your weight in kg:  80


Welcome to the BMI calculator.
Your BMI is: 27.68
You are overweight.


In [77]:
def cube_sum(n):
    # Calculate the cube sum
    sum_of_cubes = sum(i ** 3 for i in range(1, n + 1))
    return sum_of_cubes

# Get the value of n from the user
n = int(input("Enter the value of n: "))

# Check if n is valid (greater than 0)
if n <= 0:
    print("Please enter a positive integer.")
else:
    # Calculate and print the cube sum
    result = cube_sum(n)
    print(f"The cube sum of the first {n} natural numbers is: {result}")


Enter the value of n:  5


TypeError: 'int' object is not callable

In [82]:
# A formula based Python program to find sum
# of series with cubes of first n natural 
# numbers

# Returns the sum of series 
def sumOfSeries(n):
	x = (n * (n + 1) / 2)
	return (int)(x * x)



# Driver Function
n = 4
print(sumOfSeries(n))

# Code Contributed by Mohit Gupta_OMG <(0_o)>


100


In [84]:
import pandas as pd
import numpy as np

# Example DataFrame
data = {'price': [100, 200, 300, 400, 500]}
open_stock_price_df = pd.DataFrame(data)

# Convert the DataFrame column to a NumPy array and reshape it
price_array = open_stock_price_df['price'].values.reshape(-1, 1)

# Display the reshaped array
print(price_array)


[[100]
 [200]
 [300]
 [400]
 [500]]


In [85]:
import numpy as np

# Example scaled stock price data for illustration
open_stock_price_scaled = np.array([
    [0.1], [0.2], [0.3], [0.4], [0.5], [0.6], [0.7], [0.8], [0.9], [1.0]
])

# Number of previous time steps to use as features (memory state)
memory_state = 3

# Lists to store the training data
x_train = []
y_train = []

# Loop to create sequences of data
for i in range(memory_state, len(open_stock_price_scaled)):
    x_train.append(open_stock_price_scaled[i-memory_state:i, 0])
    y_train.append(open_stock_price_scaled[i, 0])

# Convert lists to numpy arrays
x_train = np.array(x_train)
y_train = np.array(y_train)

# Reshape x_train to be suitable for LSTM input
x_train = np.reshape(x_train, (x_train.shape[0], x_train.shape[1], 1))

print("X_train reshaped:")
print(x_train)
print("Y_train:")
print(y_train)


X_train reshaped:
[[[0.1]
  [0.2]
  [0.3]]

 [[0.2]
  [0.3]
  [0.4]]

 [[0.3]
  [0.4]
  [0.5]]

 [[0.4]
  [0.5]
  [0.6]]

 [[0.5]
  [0.6]
  [0.7]]

 [[0.6]
  [0.7]
  [0.8]]

 [[0.7]
  [0.8]
  [0.9]]]
Y_train:
[0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [86]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense, LSTM, Dropout
from keras import backend as K

# Example data preparation (Assuming x_train and y_train are prepared)
# Normally you would load your dataset here and preprocess it
x_train = np.array([
    [0.1, 0.2, 0.3],
    [0.2, 0.3, 0.4],
    [0.3, 0.4, 0.5],
    [0.4, 0.5, 0.6]
])

y_train = np.array([0.4, 0.5, 0.6, 0.7])

# Reshape x_train to be suitable for LSTM input (samples, timesteps, features)
x_train = np.reshape(x_train, (x_train.shape[0], x_train.shape[1], 1))

# Build the LSTM model
model = Sequential()

# Adding the first LSTM layer and some Dropout regularization
model.add(LSTM(units=50, return_sequences=True, input_shape=(x_train.shape[1], 1)))
model.add(Dropout(0.2))

# Adding a second LSTM layer and some Dropout regularization
model.add(LSTM(units=50, return_sequences=True))
model.add(Dropout(0.2))

# Adding a third LSTM layer and some Dropout regularization
model.add(LSTM(units=50, return_sequences=True))
model.add(Dropout(0.2))

# Adding a fourth LSTM layer and some Dropout regularization
model.add(LSTM(units=50))
model.add(Dropout(0.2))

# Adding the output layer
model.add(Dense(units=1))

# Compile the model
model.compile(optimizer='adam', loss='mean_squared_error')

# Train the model
model.fit(x_train, y_train, epochs=100, batch_size=32)

# Clear session to free memory after training (optional)
K.clear_session()


ModuleNotFoundError: No module named 'keras'